{% set version = "2.13.3" %}
{% set download_url = "https://github.com/git-lfs/git-lfs/releases/download" %}

package:
  name: git-lfs
  version: {{ version }}

source:
  url: {{ download_url }}/v{{ version }}/git-lfs-linux-amd64-v{{ version }}.tar.gz  # [linux]
  sha256: 03197488f7be54cfc7b693f0ed6c75ac155f5aaa835508c64d68ec8f308b04c1  # [linux]

  url: {{ download_url }}/v{{ version }}/git-lfs-darwin-amd64-v{{ version }}.zip  # [osx]
  sha256: 20509abd5291586c53e1c19768e06e7b2cf7d200cdce7b73a8ff2cfd51c49c51  # [osx]
  
  url: {{ download_url }}/v{{ version }}/git-lfs-darwin-arm64-v{{ version }}.zip  # [arm64]
  sha256: 0e845245d08036fd03eb2c1de18e6a1b0355485d73ad1d925fa9d19acc71f883  # [arm64]

  url: {{ download_url }}/v{{ version }}/git-lfs-windows-amd64-v{{ version }}.zip  # [win]
  sha256: 7997d2a6e4103af331c73db10860426cb03c5188426d27619e823358493e13e4  # [win]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-arm64-v{{ version }}.tar.gz  # [aarch64]
  sha256: 42baf1ec23e9fba197b1a62d09aab1d5dab744da6923009d6f9e4dc6d79df978  # [aarch64]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-ppc64le-v{{ version }}.tar.gz  # [ppc64le]
  sha256: bf6eafb1f9aedbdbfed6bed1b6007400d237a3ab82153908892de6ca7ad902f1  # [ppc64le]

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - git               # [unix]

test:
  commands:
    - codesign -d -vvv $(which git-lfs)             # [osx]
    - shasum -a 256 $(which git-lfs)                # [osx]
    - codesign --verify --verbose $(which git-lfs)  # [osx]
    - git-lfs --help

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.md
  summary: An open source Git extension for versioning large files

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
