{% set version = "3.4.0" %}
{% set download_url = "https://github.com/git-lfs/git-lfs/releases/download" %}

package:
  name: git-lfs
  version: {{ version }}

source:
  url: {{ download_url }}/v{{ version }}/git-lfs-linux-amd64-v{{ version }}.tar.gz  # [linux]
  sha256: 60b7e9b9b4bca04405af58a2cd5dff3e68a5607c5bc39ee88a5256dd7a07f58c  # [linux]

  url: {{ download_url }}/v{{ version }}/git-lfs-darwin-amd64-v{{ version }}.zip  # [osx]
  sha256: a1aea02201e2b15c19ae911d2c474ed400246f9721de683e70f8f52e0ae00573  # [osx]

  url: {{ download_url }}/v{{ version }}/git-lfs-darwin-arm64-v{{ version }}.zip  # [arm64]
  sha256: 114fadc3dee4ee6e29b57823b337549c823b8b0680f33190f29a5700e4b29196  # [arm64]

  url: {{ download_url }}/v{{ version }}/git-lfs-windows-amd64-v{{ version }}.zip  # [win]
  sha256: 5edafb149bc6cf7e2e8e52d18b031bdaad9a26101cc9dbbf8a3a5da03ac066f2  # [win]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-arm64-v{{ version }}.tar.gz  # [aarch64]
  sha256: aee90114f8f2eb5a11c1a6e9f1703a2bfcb4dc1fc4ba12a3a574c3a86952a5d0  # [aarch64]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-ppc64le-v{{ version }}.tar.gz  # [ppc64le]
  sha256: 1ed0277cf0ae309a4800971581ff169bbff5c865718250b11090f6a9386f7533  # [ppc64le]

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - git               # [unix]

test:
  commands:
    - codesign -d -vvv $(which git-lfs)             # [osx]
    - shasum -a 256 $(which git-lfs)                # [osx]
    - codesign --verify --verbose $(which git-lfs)  # [osx]
    - git-lfs --help

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.md
  summary: An open source Git extension for versioning large files

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
