{% set version = "2.13.1" %}
{% set download_url = "https://github.com/git-lfs/git-lfs/releases/download" %}

package:
  name: git-lfs
  version: {{ version }}

source:
  url: {{ download_url }}/v{{ version }}/git-lfs-linux-amd64-v{{ version }}.tar.gz  # [linux]
  sha256: 9eb3fac34783f600a7bf48d7e444a3e2e65bf452f8f76527806da51bedc295a4  # [linux]

  url: {{ download_url }}/v{{ version }}/git-lfs-darwin-amd64-v{{ version }}.zip  # [osx]
  sha256: e6b356167e10d894a52f32691bf6fe65658066a4d81e5980add1cc28f64cb33c  # [osx]

  url: {{ download_url }}/v{{ version }}/git-lfs-windows-amd64-v{{ version }}.zip  # [win]
  sha256: cfd2a1b65664f7a9dfafeee61d063653e626448582bd53f7c268d9a72650185d  # [win]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-arm64-v{{ version }}.tar.gz  # [aarch64]
  sha256: 0da5405aaf03aceab0e02bf1190adf0533e507325658d7a64a92836177c5050d  # [aarch64]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-ppc64le-v{{ version }}.tar.gz  # [ppc64le]
  sha256: e5486b7976547c2a473c5d4e590097b31e6519b93c64499cadeec86f08b22929  # [ppc64le]

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - git               # [unix]

test:
  commands:
    - codesign -d -vvv $(which git-lfs)             # [osx]
    - shasum -a 256 $(which git-lfs)                # [osx]
    - codesign --verify --verbose $(which git-lfs)  # [osx]
    - git-lfs --help

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.md
  summary: An open source Git extension for versioning large files

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
