travis:
  secure:
    BINSTAR_TOKEN: mPjjJSpC7LfOaefFVLUIO5kCcPBo7wdwFE27F+ZAOyUWM8e0xuicwPKTraV3vfih/4wewNJNsGTKKRU/NudFi/jTR8XGIhrJ9Yc+ZwwY27XG1v4jusqUcWibjB3GyR7d80bWLpAxCPWEyZDhLEg667i5lzD7QsDQSzuO925HqdIhKA/YkLkKQsiksa5jgKGJjO1TYuzcYvl4rqppKKOMg5OJwbxjSXYoFiCxOZFgx2Yt/L0U16SzvWFNBrxdJ3ERzb9SVkRxt86r1GluHWekxQVTuYKKeHwKTsrVaGRJXTBwqr+tRc7ACKMD8S2024xD4Im5YVB7HbJzraGtPEyBVIrYnphCLW60lQgoORLTILGyCLpR2iieOtD+98yreKnqffewfPEeWlEJ6M7hTXPHCCSYmSQyMx9xL9+XRqzwItk1IIp0m+kONgWjy/1qyVy+qxfrW5kdHsAITBq3BGSalxMPVjkAkKYqiImrhjJ7z5N8FtgUKlkZSKzeeSiU6KHCY/EMZ+LDNHYfFMk7DSWkgQ/iVIyOtJCJTNSeUXI0/7r18CL6SdBhAuUtz9X62+4X6bWQEyH0V5ow/6gPQhagI/5hNV3MfFyDGscPazKaAvC23X86R8IkD9HwnIli4ZDO2sjKs6oSV9zMNq1rfPsLCoNE+wQkvQErgIWP4CEESmo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
